"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var persona_1 = require("./persona");
var juegoGenerala_1 = require("./juegoGenerala");
var cubilete_1 = require("./cubilete");
var presycred_1 = require("./presycred");
var jug1 = new persona_1.Persona("Cristian", "Falcone", 26134695, new Date(1977, 10, 7), "Cypher");
var jug2 = new persona_1.Persona("Natalia", "Tutora", 33333333, new Date(2000, 10, 7), "Naty");
var dado1 = new cubilete_1.Dado;
var dado2 = new cubilete_1.Dado;
var dado3 = new cubilete_1.Dado;
var dado4 = new cubilete_1.Dado;
var dado5 = new cubilete_1.Dado;
var cubilete = new cubilete_1.Cubilete([dado1, dado2, dado3, dado4, dado5]);
var tirada1 = new juegoGenerala_1.Generala(cubilete);
(0, presycred_1.presentacion)(jug1.nickname, jug2.nickname);
tirada1.multiplayer(4, jug1, jug2);
(0, presycred_1.creditos)();
