import { Televisor } from "./Televisor";

const TV1 = new Televisor("TLC");   
TV1.switchPower(); 
TV1.info();
TV1.volumeUp();
TV1.volumeUp();
TV1.muteOnOff();
TV1.volumeUp();
TV1.volumeDown();
TV1.volumeDown();
TV1.volumeDown();
TV1.volumeDown();
TV1.volumeUp();
TV1.info();
TV1.switchPower(); 
TV1.info();
TV1.volumeUp();
TV1.volumeUp();
TV1.volumeUp();
TV1.volumeUp();
TV1.info();
TV1.switchPower();
TV1.volumeUp();
TV1.info();
TV1.switchPower();
TV1.info();
TV1.channelUp;
TV1.channelUp;
TV1.channelUp;
TV1.switchPower();
TV1.info();
TV1.channelDown();
TV1.channelDown();
TV1.info();
