"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Auto_1 = require("./Auto");
var datos_1 = require("./datos");
var auto1 = new datos_1.Auto("Ford", "Falcon SP", "3.6L", "XKP371218", "WHI906");
var auto2 = new datos_1.Auto("Ford", "Falcon XP", "3.7L", "XKP371218", "WHI906");
var RegistroAutomotor1 = new Auto_1.RegistroAutomotor(datos_1.arrayAutos);
var indiceV1;
var indiceV2;
RegistroAutomotor1.agregarVehiculo(auto1);
RegistroAutomotor1.mostrarListadoVehiculos();
indiceV1 = RegistroAutomotor1.buscarVehiculoPatente("WHI906");
indiceV2 = RegistroAutomotor1.buscarVehiculoPatente("RS678TU");
//RegistroAutomotor1.eliminarVehiculo("WHI906");
RegistroAutomotor1.eliminarVehiculo("EF456GH");
RegistroAutomotor1.mostrarListadoVehiculos();
RegistroAutomotor1.eliminarVehiculo("EF45UUU");
RegistroAutomotor1.modificarVehiculo("WHI906", auto2);
RegistroAutomotor1.mostrarListadoVehiculos();
